server:
  port: 13000
spring:
  profiles:
    active: local
  application:
    name: heltnote-api

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://itsinil@localhost:8761/eureka
  instance:
    hostname: localhost